### PR TITLE
#17_configured_&_addded_dotenv

### PR DESCRIPTION
**Pull request by IRSHIT033**
This PR tries to resolve https://github.com/bhavik2936/speed-reader/issues/17.

## What
  1. Adding and Configuring Dotenv Dependency
  2. added " dotenv " package in package.json
  3. Configured webpack , using DefinePlugin module .

## Outcome
now user can use ".env" file to secure their "Api keys " and confidencial stuffs .

## Screenshots (just for showing added a env variable not added this in "App.js")
Screenshot (51)

### CODE REVIEW

**Comment by IRSHIT033** [comment]
@bhavik2936 can u check once more

**Review by bhavik2936 — CHANGES_REQUESTED** [review]
Thanks for changes Irshit. **Dotenv** changes looks good but, as currently we are not planning to migrate from single quoted to double quoted strings.

Let's revert the changes by [amending](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend) new changes followed by [force](https://git-scm.com/docs/git-push#Documentation/git-push.txt---force-with-leaseltrefnamegt) push in the same branch. Which will reflect changes into the same PR. (If you're comfortable with creating a new commit; that will work as well)

**Comment by IRSHIT033** [comment]
@bhavik2936 done.....thnx for telling me about "amend" and "force" flag its awesome man.

**Comment by IRSHIT033** [comment]
@bhavik2936  can  u check again?

**Review by bhavik2936 — APPROVED** [review]
Couple of extra changes, but won't block it.
Looks Good!

**Comment by bhavik2936** [comment]
Hey @IRSHIT033, thanks again for the contribution. I am sharing a reference to [LearnGitBranching](https://learngitbranching.js.org), wherein one can sharpen their skills on git branching & remote in an interactive way. Hope you like it!

**Pull request merged**
